#cloud-config

# /var/log/cloud-init-output.log for debugging this script 

# openresty nginx logs in /usr/local/openresty/nginx/logs/error.log and access.log
# nginx conf in /usr/local/openresty/nginx/conf
# to restart openresty after a conf update: sudo systemctl restart openresty

# ~/testout.txt for the dotnet test output

package_upgrade: true
runcmd:
  # install dotnet
  - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo add-apt-repository universe -y
  - sudo apt-get update -y
  - sudo apt-get install apt-transport-https -y
  - sudo apt-get update -y

  # need the sdk as we'll be compiling
  - sudo apt-get install dotnet-sdk-3.1 -y

  # nginx
  - sudo apt-get install nginx -y

  # a nice shortcut sym link
  # - sudo ln -s /var/www/ /home/dave/www

  # a nice restart command for nginx
  - cd /home/dave
  - echo "sudo systemctl restart nginx" > s.sh
  - sudo chmod 777 s.sh

  # clone source
  - cd /home/dave
  - sudo git clone https://github.com/djhmateer/postgres-cookie-dave.git source

  # run the tests on the server as a last ditch safety net (make sure tests run linux side)
  - cd source/src/PostgresCookieDave.Web.IntegrationTests
  - sudo dotnet test -v n > /home/dave/testout.txt

  # publish the web app
  - cd /home/dave/source/src/PostgresCookieDave.Web
  - sudo dotnet publish --configuration Release 

  # copy files to www directory
  - cd /home/dave/source/src/PostgresCookieDave.Web/bin/Release/netcoreapp3.1/publish/
  - sudo mkdir /var/www/web
  - sudo cp -a * /var/www/web/.

  # change ownership of the files - TODO review this
  - sudo chown -R www-data:www-data /var/www/web

  # nginx config
  - sudo cp /home/dave/source/infra/nginx.conf /etc/nginx/sites-available/default
  - sudo nginx -s reload

  # get rid of the default nginx files
  - sudo rm -rf /var/www/html

  # make the systemd service to keep Kestrel alive
  - sudo cp /home/dave/source/infra/kestrel.service /etc/systemd/system/kestrel.service
  - sudo systemctl enable kestrel.service
  - sudo systemctl start kestrel.service

  #
  # Bashtop
  #
  - echo "deb http://packages.azlux.fr/debian/ buster main" | sudo tee /etc/apt/sources.list.d/azlux.list
  - sudo wget -qO - https://azlux.fr/repo.gpg.key | sudo apt-key add -
  - sudo apt update -y
  - sudo apt install bashtop -y

  # Postgres
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -y install postgresql

  - sudo systemctl start postgresql@12-main

# make a quick test page to signify that the server is ready to go
  # - cd /var/www/cookie-dave-web
  # - echo "Healthy" > healthcheck.html

# OS updates need a reboot 
  - sudo reboot now